# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ed/workspace/git_repos/predictor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ed/workspace/git_repos/predictor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ed/workspace/git_repos/predictor/CMakeFiles /home/ed/workspace/git_repos/predictor/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ed/workspace/git_repos/predictor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named predictor

# Build rule for target.
predictor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 predictor
.PHONY : predictor

# fast build rule for target.
predictor/fast:
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/build
.PHONY : predictor/fast

dependencies/pugixml/src/pugixml.o: dependencies/pugixml/src/pugixml.cpp.o

.PHONY : dependencies/pugixml/src/pugixml.o

# target to build an object file
dependencies/pugixml/src/pugixml.cpp.o:
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/dependencies/pugixml/src/pugixml.cpp.o
.PHONY : dependencies/pugixml/src/pugixml.cpp.o

dependencies/pugixml/src/pugixml.i: dependencies/pugixml/src/pugixml.cpp.i

.PHONY : dependencies/pugixml/src/pugixml.i

# target to preprocess a source file
dependencies/pugixml/src/pugixml.cpp.i:
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/dependencies/pugixml/src/pugixml.cpp.i
.PHONY : dependencies/pugixml/src/pugixml.cpp.i

dependencies/pugixml/src/pugixml.s: dependencies/pugixml/src/pugixml.cpp.s

.PHONY : dependencies/pugixml/src/pugixml.s

# target to generate assembly for a file
dependencies/pugixml/src/pugixml.cpp.s:
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/dependencies/pugixml/src/pugixml.cpp.s
.PHONY : dependencies/pugixml/src/pugixml.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/main.cpp.s
.PHONY : main.cpp.s

predictor.o: predictor.cpp.o

.PHONY : predictor.o

# target to build an object file
predictor.cpp.o:
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/predictor.cpp.o
.PHONY : predictor.cpp.o

predictor.i: predictor.cpp.i

.PHONY : predictor.i

# target to preprocess a source file
predictor.cpp.i:
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/predictor.cpp.i
.PHONY : predictor.cpp.i

predictor.s: predictor.cpp.s

.PHONY : predictor.s

# target to generate assembly for a file
predictor.cpp.s:
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/predictor.cpp.s
.PHONY : predictor.cpp.s

weather.o: weather.cpp.o

.PHONY : weather.o

# target to build an object file
weather.cpp.o:
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/weather.cpp.o
.PHONY : weather.cpp.o

weather.i: weather.cpp.i

.PHONY : weather.i

# target to preprocess a source file
weather.cpp.i:
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/weather.cpp.i
.PHONY : weather.cpp.i

weather.s: weather.cpp.s

.PHONY : weather.s

# target to generate assembly for a file
weather.cpp.s:
	$(MAKE) -f CMakeFiles/predictor.dir/build.make CMakeFiles/predictor.dir/weather.cpp.s
.PHONY : weather.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... predictor"
	@echo "... dependencies/pugixml/src/pugixml.o"
	@echo "... dependencies/pugixml/src/pugixml.i"
	@echo "... dependencies/pugixml/src/pugixml.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... predictor.o"
	@echo "... predictor.i"
	@echo "... predictor.s"
	@echo "... weather.o"
	@echo "... weather.i"
	@echo "... weather.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

